---
- name: create servers
  hosts: localhost
  gather_facts: False
  vars:
    sl_datacenter: dal09
    sl_ssh_key: 926125
    sl_vlan: 1919743
    etc_hosts: ~

  tasks:
    - name: create master
      sl_vm:
        hostname: "{{ item }}"
        domain: icp.example.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},icp,master"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 2
        memory: 4096
        disks: [100]
        os_code: CENTOS_LATEST
        private_vlan: "{{ sl_vlan|default(omit) }}"
        wait: no
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - master01

    - name: create workers
      sl_vm:
        hostname: "{{ item }}"
        domain: icp.example.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},icp,worker"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 2
        memory: 4096
        disks: [100]
        os_code: CENTOS_LATEST
        private_vlan: "{{ sl_vlan|default(omit) }}"
        wait: no
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - worker01
        - worker02
